name: signalr_netcore
description: A flutter client for ASP.NET Core SignalR. The client is able to invoke server side hub functions and to receive method invocations issued by the server.
version: 1.3.5
homepage: https://github.com/sefidgaran/signalr_client

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  logging: ^1.0.1
  http: ^1.1.0
  web_socket_channel: ^2.1.0
  message_pack_dart: ^2.0.1
  sse_channel: 
    git: https://github.com/brinkler/sse_channel.git

publish_to: none

dev_dependencies:
  test: "^1.16.2"
  collection: ^1.15.0
  flutter_test:
    sdk: flutter
# The following section is specific to Flutter.
flutter: